---
ci:
  autofix_commit_msg: "Chore: pre-commit autoupdate"

exclude: |
  (?x)^(
      docs\/conf.py|
      dco-signoffs/$
  )$

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      # - id: detect-aws-credentials
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: mixed-line-ending
      #  args: ["--fix=lf"]
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: no-commit-to-branch
      # - id: pretty-format-json
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea  # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args:
          ['--no-error-on-unmatched-pattern', '--ignore-unknown']

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 192ad822316c3a22fb3d3cc8aa6eafa0b8488360  # frozen: v0.45.0
    hooks:
      - id: markdownlint
        args: ["--fix"]

  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98  # frozen: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/openstack/bashate
    rev: 5798d24d571676fc407e81df574c1ef57b520f23  # frozen: 2.1.1
    hooks:
      - id: bashate
        args: ["--ignore=E006,E011"]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95  # frozen: v0.11.0.1
    hooks:
      - id: shellcheck
        args: ["-x"]  # Check external files

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: f999ae59ac949d9b57aaa5569c2d60eb846b3a00  # frozen: v1.7.7.24
    hooks:
      - id: actionlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7  # frozen: v1.37.1
    hooks:
      - id: yamllint
        args:
          ["-d", "{rules: {line-length: {max: 120}},
          ignore-from-file: [.gitignore],}"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: a113f03edeabb71305f025e6e14bd2cd68660e29  # frozen: v0.13.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=pyproject.toml]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy-cache
        name: "create mypy cache"
        language: system
        pass_filenames: false
        entry: bash -c 'if [ ! -d .mypy_cache ];
          then /bin/mkdir .mypy_cache; fi; exit 0'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "9f70dc58c23dfcca1b97af99eaeee3140a807c7e"  # frozen: v1.18.2
    hooks:
      - id: mypy
        verbose: true
        args: ["--show-error-codes", "--install-types", "--non-interactive"]
        additional_dependencies: ["pytest", "types-requests"]

# yamllint disable rule:comments-indentation
  # Check for misspellings in documentation files
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.2
  #   hooks:
  #     - id: codespell

  # Automatically upgrade Python syntax for newer versions
  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v3.15.0
  #   hooks:
  #     - id: pyupgrade
  #       args: ['--py37-plus']
# yamllint enable rule:comments-indentation
